{"version":3,"file":"static/webpack/static\\development\\pages\\_app.js.a2be6897ede0749c7038.hot-update.js","sources":["webpack:///./sagas/user.js"],"sourcesContent":["import { all, fork, takeLatest, call, put, take } from 'redux-saga/effects';\r\nimport { LOG_IN_SUCCESS, LOG_IN_FAILURE, LOG_IN } from '../reducers/user';\r\n\r\n\r\n// take -> redux-saga에서 generator.next()와 마찬가지로 yield 로인해 중단된 함수를 다시 재개시킨다.\r\n\r\nconst HELLO_SAGA = 'HELLO_SAGA';\r\n\r\nfunction* loginAPI() {\r\n  // 서버에 요청을 보내는 부분\r\n}\r\n\r\nfunction* login() {\r\n  try {\r\n    yield call(loginAPI);\r\n    yield put({ // loginAPI 성공 put은 dispatch와 동일\r\n      type: LOG_IN_SUCCESS\r\n    });\r\n  } catch (e) { // loginAPI 실패\r\n    console.error(e);\r\n    yield put({\r\n      type: LOG_IN_FAILURE\r\n    });\r\n  }\r\n}\r\n\r\nfunction* watchLogin() {\r\n  yield takeLatest(LOG_IN, login)\r\n}\r\nfunction* helloSaga() {\r\n  yield take(HELLO_SAGA);\r\n}\r\n\r\nexport default function* userSaga() {\r\n  yield helloSaga();\r\n}"],"mappings":";;;;;;;;;;;;;;;;;;;;AAQA;;;AAIA;;;AAcA;;;AAGA;;;AAIA;AACA;AAlCA;AACA;AACA;AAIA;AACA;AACA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AACA;AAGA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAEA;AACA;AAHA;AAAA;AAGA;AAAA;AACA;AADA;AACA;AAJA;AAAA;AAAA;AACA;AADA;AAAA;AAAA;AAMA;AACA;AAPA;AAQA;AACA;AADA;AACA;AATA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AACA;AAaA;AAAA;AAAA;AAAA;AAAA;AAAA;AACA;AACA;AAFA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AACA;AAEA;AAAA;AAAA;AAAA;AAAA;AAAA;AACA;AACA;AAFA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AACA;AAGA;AAAA;AAAA;AAAA;AAAA;AAAA;AACA;AACA;AAFA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;;;;A","sourceRoot":""}